CREATE TABLE traduction (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	filename VARCHAR(100) NOT NULL,
	sequence VARCHAR(150) NOT NULL

) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;


CREATE TABLE strings (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	translated_str TINYTEXT,
	language_str VARCHAR(20) NOT NULL,
	traduction_id BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
